apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helep.fullname" . }}-config
  labels:
    {{- include "helep.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP: {{ .Values.global.kafkaBootstrap | quote }}
