{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-data
  labels:
    {{- include "helep.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if $.Values.global.storageClassName }}
  storageClassName: {{ $.Values.global.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
{{- end }}
