apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helep.fullname" . }}-secret
  labels:
    {{- include "helep.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
