{{- if .Values.serviceMonitor.enabled }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  labels:
    {{- include "helep.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
